USE [Artsent_S_A_PRUEBA1]
GO

/****** Object:  Table [dbo].[NUMEROS_PEDIDOS_SISTEMA_VENTAS]    Script Date: 11/11/2021 17:52:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NUMEROS_PEDIDOS_SISTEMA_VENTAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRIMER_PEDIDO] [varchar](50) NOT NULL,
	[SEGUNDO_PEDIDO] [varchar](50) NOT NULL,
	[TERCER_PEDIDO] [varchar](50) NOT NULL,
	[SEÑA] [varchar](50) NULL,
	[TOTAL_IMPORTE_PEDIDO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_NUMEROS_PEDIDOS_SISTEMA_VENTAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

