USE [Artsent_S_A_PRUEBA1]
GO

/****** Object:  Table [dbo].[SEIN_RELACION_PEDIDOS_REMITOS_SISTEMA]    Script Date: 11/11/2021 17:57:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEIN_RELACION_PEDIDOS_REMITOS_SISTEMA](
	[TALON_PED] [varchar](5) NOT NULL,
	[NRO_PEDIDO] [varchar](20) NOT NULL,
	[NCOMP_IN_S] [varchar](8) NULL,
	[TCOMP_IN_S] [varchar](5) NULL,
 CONSTRAINT [PK_NroPedidoTalonPedRemitos] PRIMARY KEY CLUSTERED 
(
	[TALON_PED] ASC,
	[NRO_PEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

